# File Options
files:
  include: 'app/assets/stylesheets/**/*.s+(a|c)ss'
# Rules
rules:
  class-name-format:
    - allow-leading-underscore: true
    - convention: hyphenatedbem
  mixins-before-declarations:
    - 1
    - exclude: ['tablet', 'desktop']
  nesting-depth:
    - 1
    - max-depth: 3
